a15x: Disable ELF checks for all consumers of mtkpower
Something really broke after switching to oss mtkpower and these have nonsensical
ELF check errors that will not go away.

Effectively, all of them spit out:

error: DT_NEEDED "vendor.mediatek.hardware.mtkpower@1.0.so" is not specified in shared_libs.

Despite the lib being in shared_libs.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>