a15x: Add libmtkperf_client namespace to vendor
Needed by some blobs now that mtkpower is not prebuilt.

[100% 2/2] analyzing Android.bp files and generating ninja file at out/soong/build.pixelage_a15x.ninja
FAILED: out/soong/build.pixelage_a15x.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     --soong_variables out/soong/soong.pixelage_a15x.variables -o out/soong/build.pixelage_a15x.ninja -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.pixelage_a15x.build Android.bp
Warning: Module 'androidx.wear_wear' depends on non-existing optional_uses_libs 'wear-sdk'
Warning: Module 'androidx.wear.compose_compose-foundation' depends on non-existing optional_uses_libs 'wear-sdk'
error: vendor/samsung/a15x/Android.bp:26824:1: "libh264dec_sd.ca7" depends on undefined module "libpowerhalwrap_vendor".
Module "libh264dec_sd.ca7" is defined in namespace "vendor/samsung/a15x" which can read these 5 namespaces: ["vendor/samsung/a15x" "device/samsung/a15x" "hardware/samsung" "hardware/mediatek" "."]
Module "libpowerhalwrap_vendor" can be found in these namespaces: ["hardware/mediatek/libmtkperf_client"]
Or did you mean ["//libcore/expectations" "//libcore/toolchainapi" "power_tracker_headers"]?
error: vendor/samsung/a15x/Android.bp:26654:1: "libHEVCdec_sa.ca7.android" depends on undefined module "libpowerhalwrap_vendor".
Module "libHEVCdec_sa.ca7.android" is defined in namespace "vendor/samsung/a15x" which can read these 5 namespaces: ["vendor/samsung/a15x" "device/samsung/a15x" "hardware/samsung" "hardware/mediatek" "."]
Module "libpowerhalwrap_vendor" can be found in these namespaces: ["hardware/mediatek/libmtkperf_client"]
Or did you mean ["//libcore/expectations" "//libcore/toolchainapi" "power_tracker_headers"]?
error: vendor/samsung/a15x/Android.bp:27248:1: "libvp9dec_sa.ca7" depends on undefined module "libpowerhalwrap_vendor".
Module "libvp9dec_sa.ca7" is defined in namespace "vendor/samsung/a15x" which can read these 5 namespaces: ["vendor/samsung/a15x" "device/samsung/a15x" "hardware/samsung" "hardware/mediatek" "."]
Module "libpowerhalwrap_vendor" can be found in these namespaces: ["hardware/mediatek/libmtkperf_client"]
Or did you mean ["//libcore/expectations" "//libcore/toolchainapi" "power_tracker_headers"]?
error: vendor/samsung/a15x/Android.bp:26855:1: "libh264dec_se.ca7" depends on undefined module "libpowerhalwrap_vendor".
Module "libh264dec_se.ca7" is defined in namespace "vendor/samsung/a15x" which can read these 5 namespaces: ["vendor/samsung/a15x" "device/samsung/a15x" "hardware/samsung" "hardware/mediatek" "."]
Module "libpowerhalwrap_vendor" can be found in these namespaces: ["hardware/mediatek/libmtkperf_client"]
Or did you mean ["//libcore/expectations" "//libcore/toolchainapi" "power_tracker_headers"]?
00:27:24 soong bootstrap failed with: exit status 1

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>